---
- name: Installed and Start Apache
  hosts: localhost
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: installed
  - name: Start and Enable Apache
    systemd:
      name: httpd
      enabled: yes
      state: started
      